#!/bin/bash
set -f # disables globbing
EXPERIMENT_MAIN_PATH=$(dirname $0)
set +f

"${EXPERIMENT_MAIN_PATH}"/experiment_0.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_1.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_2.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_3.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_4.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_5.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_6.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_7.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_8.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_9.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_10.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_11.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_12.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_13.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_14.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_15.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_16.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_17.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_18.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_19.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_20.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_21.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_22.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_23.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_24.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_25.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_26.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_27.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_28.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_29.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_30.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_31.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_32.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_33.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_34.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_35.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_36.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_37.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_38.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_39.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_40.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_41.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_42.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_43.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_44.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_45.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_46.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_47.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_48.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_49.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_50.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_51.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_52.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_53.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_54.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_55.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_56.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_57.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_58.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_59.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_60.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_61.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_62.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_63.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_64.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_65.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_66.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_67.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_68.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_69.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_70.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_71.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_72.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_73.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_74.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_75.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_76.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_77.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_78.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_79.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_80.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_81.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_82.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_83.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_84.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_85.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_86.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_87.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_88.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_89.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_90.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_91.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_92.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_93.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_94.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_95.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_96.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_97.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_98.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_99.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_100.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_101.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_102.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_103.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_104.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_105.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_106.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_107.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_108.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_109.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_110.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_111.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_112.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_113.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_114.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_115.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_116.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_117.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_118.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_119.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_120.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_121.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_122.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_123.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_124.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_125.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_126.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_127.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_128.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_129.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_130.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_131.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_132.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_133.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_134.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_135.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_136.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_137.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_138.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_139.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_140.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_141.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_142.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_143.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_144.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_145.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_146.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_147.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_148.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_149.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_150.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_151.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_152.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_153.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_154.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_155.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_156.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_157.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_158.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_159.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_160.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_161.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_162.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_163.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_164.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_165.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_166.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_167.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_168.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_169.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_170.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_171.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_172.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_173.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_174.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_175.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_176.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_177.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_178.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_179.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_180.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_181.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_182.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_183.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_184.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_185.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_186.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_187.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_188.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_189.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_190.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_191.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_192.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_193.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_194.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_195.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_196.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_197.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_198.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_199.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_200.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_201.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_202.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_203.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_204.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_205.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_206.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_207.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_208.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_209.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_210.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_211.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_212.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_213.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_214.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_215.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_216.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_217.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_218.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_219.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_220.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_221.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_222.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_223.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_224.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_225.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_226.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_227.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_228.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_229.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_230.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_231.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_232.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_233.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_234.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_235.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_236.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_237.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_238.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_239.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_240.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_241.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_242.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_243.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_244.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_245.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_246.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_247.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_248.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_249.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_250.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_251.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_252.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_253.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_254.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_255.run.sh
