#!/bin/bash
set -f # disables globbing
EXPERIMENT_MAIN_PATH=$(dirname $0)
set +f

"${EXPERIMENT_MAIN_PATH}"/experiment_8.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_9.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_10.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_11.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_24.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_25.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_26.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_27.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_28.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_29.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_30.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_31.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_32.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_33.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_34.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_35.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_36.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_37.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_38.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_39.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_40.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_41.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_42.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_43.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_44.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_45.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_46.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_47.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_52.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_53.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_54.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_55.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_64.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_65.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_66.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_67.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_76.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_77.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_78.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_79.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_84.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_85.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_86.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_87.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_92.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_93.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_94.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_95.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_100.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_101.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_102.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_103.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_112.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_113.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_114.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_115.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_116.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_117.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_118.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_119.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_120.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_121.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_122.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_123.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_128.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_129.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_130.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_131.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_140.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_141.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_142.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_143.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_144.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_145.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_146.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_147.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_152.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_153.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_154.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_155.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_156.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_157.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_158.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_159.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_172.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_173.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_174.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_175.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_192.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_193.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_194.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_195.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_196.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_197.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_198.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_199.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_204.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_205.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_206.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_207.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_208.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_209.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_210.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_211.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_220.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_221.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_222.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_223.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_236.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_237.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_238.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_239.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_240.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_241.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_242.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_243.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_244.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_245.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_246.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_247.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_248.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_249.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_250.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_251.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_252.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_253.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_254.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_255.run.sh
