#!/bin/bash
set -f # disables globbing
EXPERIMENT_MAIN_PATH=$(dirname $0)
set +f

"${EXPERIMENT_MAIN_PATH}"/experiment_0.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_1.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_2.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_3.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_4.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_5.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_6.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_7.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_8.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_9.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_10.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_11.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_12.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_13.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_14.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_15.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_16.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_17.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_18.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_19.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_20.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_21.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_22.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_23.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_24.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_25.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_26.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_27.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_28.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_29.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_30.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_31.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_32.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_33.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_34.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_35.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_36.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_37.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_38.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_39.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_40.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_41.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_42.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_43.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_44.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_45.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_46.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_47.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_48.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_49.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_50.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_51.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_52.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_53.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_54.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_55.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_56.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_57.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_58.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_59.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_60.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_61.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_62.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_63.run.sh
