#!/bin/bash
set -f # disables globbing
EXPERIMENT_MAIN_PATH=$(dirname $0)
set +f

"${EXPERIMENT_MAIN_PATH}"/experiment_0.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_1.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_2.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_3.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_4.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_5.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_6.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_7.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_16.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_17.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_18.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_19.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_20.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_21.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_22.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_23.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_48.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_49.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_50.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_51.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_52.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_53.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_54.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_55.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_80.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_81.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_82.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_83.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_84.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_85.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_86.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_87.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_88.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_89.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_90.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_91.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_92.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_93.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_94.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_95.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_96.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_97.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_98.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_99.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_100.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_101.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_102.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_103.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_104.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_105.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_106.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_107.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_108.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_109.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_110.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_111.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_112.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_113.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_114.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_115.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_116.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_117.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_118.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_119.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_120.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_121.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_122.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_123.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_124.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_125.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_126.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_127.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_136.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_137.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_138.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_139.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_140.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_141.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_142.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_143.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_160.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_161.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_162.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_163.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_164.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_165.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_166.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_167.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_184.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_185.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_186.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_187.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_188.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_189.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_190.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_191.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_200.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_201.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_202.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_203.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_204.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_205.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_206.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_207.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_216.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_217.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_218.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_219.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_220.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_221.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_222.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_223.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_232.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_233.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_234.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_235.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_236.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_237.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_238.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_239.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_256.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_257.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_258.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_259.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_260.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_261.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_262.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_263.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_264.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_265.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_266.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_267.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_268.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_269.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_270.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_271.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_272.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_273.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_274.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_275.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_276.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_277.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_278.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_279.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_288.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_289.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_290.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_291.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_292.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_293.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_294.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_295.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_312.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_313.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_314.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_315.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_316.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_317.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_318.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_319.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_320.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_321.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_322.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_323.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_324.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_325.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_326.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_327.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_336.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_337.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_338.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_339.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_340.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_341.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_342.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_343.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_344.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_345.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_346.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_347.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_348.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_349.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_350.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_351.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_376.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_377.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_378.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_379.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_380.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_381.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_382.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_383.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_416.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_417.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_418.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_419.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_420.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_421.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_422.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_423.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_424.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_425.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_426.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_427.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_428.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_429.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_430.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_431.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_440.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_441.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_442.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_443.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_444.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_445.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_446.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_447.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_448.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_449.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_450.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_451.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_452.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_453.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_454.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_455.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_472.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_473.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_474.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_475.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_476.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_477.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_478.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_479.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_504.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_505.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_506.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_507.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_508.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_509.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_510.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_511.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_512.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_513.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_514.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_515.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_516.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_517.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_518.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_519.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_520.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_521.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_522.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_523.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_524.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_525.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_526.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_527.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_528.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_529.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_530.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_531.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_532.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_533.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_534.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_535.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_536.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_537.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_538.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_539.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_540.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_541.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_542.run.sh
"${EXPERIMENT_MAIN_PATH}"/experiment_543.run.sh
